node fetch.js parser_configs/borderline_biz.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/empireflippers_marketplace.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/feinternational_buy-a-website.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/flippa_amazon_fba.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/flippa_android.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/flippa_ios.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/flippa_web.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/githustle_developer_projects.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/news_ycombinator_com.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/opengameart.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/reddit_side_project.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/sideprojectors.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
node fetch.js parser_configs/transferslot.json https://LAMBDA-PATH.execute-api.us-west-2.amazonaws.com/production/site-parser
